### ISSUE TITLE
Add test case to verify vote out of the DB

### ISSUE THREAD

**Issue by paultag** [opencivicdata/pupa#181] opened 2015-05-19 14:51 UTC
https://github.com/opencivicdata/pupa/pull/178 <-- let's also do an `Event.objects.get` and check the import pipeline

**Comment by jamesturk** [comment] 2015-10-07 02:47
@paultag do you remember what you're looking for here?

**Comment by jpmckinney** [comment] 2017-02-03 23:36
Closing for lack of clarity.

**Closed by jpmckinney** 2017-02-03 23:36 UTC

**Comment by jpmckinney** [comment] 2017-02-03 23:43
I think maybe the issue is adding another test related to this PR: https://github.com/opencivicdata/pupa/pull/178/files
